### ISSUE TITLE
Add heartbeat functionality

### ISSUE THREAD

**Issue by kensiprell** [kensiprell/browser-websocket-client#7]
Options section:
Name (appears in dropdown menu)
Delay before sending first heartbeat message (in seconds)
Frequency to send heartbeat message from client (in seconds)
Message (JSON checking enabled/disabled)

Client section:
Choose by name dropdown
Start -> Stop buttons

Questions:
Allow JavaScript functions in heartbeat message from client, e.g. `new Date()`
Show time last heartbeat message sent from client
Show time last heartbeat message received from server

**Comment by kensiprell** [comment]
@vkulpa Please leave some feedback on this issue. Thanks!

**Comment by vkulpa** [comment]
@kensiprell I'll take a look at it later and give some feedback

**Comment by kensiprell** [comment]
I've done some initial work in the 1.4.0 branch, mostly HTML. At least you can get an idea where I'm going with this. If anything is not clear to you or you have other ideas and suggestions, please let me know.

**Comment by vkulpa** [comment]
I've checked the 1.4.0 branch. I think `initial delay` is odd and could be omitted because we have `frequency`. Also, I'd prefer having `message from server` text field configurable and maybe option to ignore that message in message area, since we have `track heartbet` I don't want to see PONG messages in message area.

The rest looks great. I like it, thank you for the update.

**Comment by kensiprell** [comment]
Thanks for the feedback. I agree with your comments on the initial delay and not displaying pong messages. I'll remove the delay input and add an option to avoid displaying the server messages.

However, I'm not sure what you mean with "I'd prefer having message from server text field configurable." Could you explain that in more detail? 

My plan is to search all incoming messages for either a string or an object key depending on what the user selected. Does that make sense? Otherwise, I'm not sure how to make the ping/pong work for everyone. Ideas are welcome.

One Firefox user left a bad review because the extension doesn't support authentication, but I couldn't imagine how I could do that and cover all possible scenarios. I don't want to incorporate functionality for a single use case.

**Comment by vkulpa** [comment]
I meant ping/pong messages are specific for client/server implementation. Plugin should have ability to specify ping and pong message content separately in order to ignore those settings in message area. For example, my WS communication uses "2" as ping and "3" as pong. I'd like to be able specify those via text fields in "heartbeats" section and if I chose proper setting it also should be ignored in message area - both - ping and pong. Does it make sense? What do you think?

I'll take a look at authentication tomorrow and see what could be done as general scenario.

**Comment by vkulpa** [comment]
I took a quick loot at Authentication/Authorization. It might be Cookie/Token based. In other words when client initializes connection it should pass `valid` Cookie or `Authorization` header (e.g. `Authorization: Bearer valid-token`, `Cookie: sid=valid-sid`

**Comment by kensiprell** [comment]
There is an input field for entering the server message. It appears after selecting a server message type from the dropdown although I still have to think about how the user would enter an object (I prefer dot.notation). I'm trying to make this section as uncluttered and self-explanatory as possible, and apparently I failed. I'll take another look at it since it wasn't obvious to you.

I personally use an Authorization header with a JWT, but then do I copy and paste the token from somewhere into the extension? How would I set the cookie? These are the questions I can't answer in advance, and implementing a login that would work for everyone seems impossible to me since one can use a different library, message format, etc. However, as always I'm open to suggestions.

**Comment by vkulpa** [comment]
Ah, yes, I've found where I could specify message from server. I think you made that section great. There's no overhead in visibility if user doesn't want to track or specify message from server. I think, it's fine as it's right now.

There's no another way than copy/paste authorization token or cookie values, I guess. How to pass it?! Need to investigate it as well.

**Comment by kensiprell** [comment]
@vkulpa I wanted to give you an update, so you don't think I've forgotten about this issue. I wasn't happy with the user interface, and it took me awhile to come up with something I like. Now I have the HTML and the JavaScript for validating and saving a heartbeat basically finished. 

Right now I'm working on the logic for parsing server messages and updating the UI in the client section. Once I finish this part and tidy up the rest, I'll probably push those changes and ask you to take another look and give me feedback. Then I'll have to update the tests and fix bugs (there are always several) before the next release.

**Comment by vkulpa** [comment]
Cool, thank you for the update. Sorry, I haven't had a chance to respond and take a look yet.

**Comment by kensiprell** [comment]
Closing due to lack of feedback.
